[package]
name = "exp-async-rust-wasmtime"
version = "0.1.0"
authors = ["Philipp Muens <raute1337@gmx.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
wasmtime = "0.23.0"

[[bin]]
name = "bin"
path = "src/bin.rs"
